/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_elicoinwallet_core_ethereum_BREthereumToken */

#ifndef _Included_com_elicoinwallet_core_ethereum_BREthereumToken
#define _Included_com_elicoinwallet_core_ethereum_BREthereumToken
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_elicoinwallet_core_ethereum_BREthereumToken
 * Method:    jniGetTokenBRD
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_elicoinwallet_core_ethereum_BREthereumToken_jniGetTokenBRD
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
